app:
  name: "go-api-mono"
  version: "1.0.0"
  mode: "development"

server:
  port: 2024
  readTimeout: "10s"
  writeTimeout: "10s"
  shutdownTimeout: "30s"
  addr: ":2024"

log:
  level: "debug"
  filename: "logs/app.log"
  maxSize: 100
  maxBackups: 10
  maxAge: 7
  compress: true

database:
  host: "localhost"
  port: 3306
  username: "apiuser"
  password: "apipass"
  database: "go_api_mono"
  maxOpenConns: 100
  maxIdleConns: 10
  maxLifetime: "1h"
  debug: true

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

jwt:
  signingKey: "your-secret-key-change-it-in-production-32"
  expirationTime: "24h"
  signingMethod: "HS256"
  tokenPrefix: "Bearer"

rateLimit:
  enabled: true
  limit: 100    # 每秒允许的请求数
  burst: 200    # 突发请求数