app:
  name: "go-api-mono"
  version: "1.0.0"
  mode: "development"

server:
  port: 8080
  readTimeout: "10s"
  writeTimeout: "10s"
  shutdownTimeout: "30s"
  addr: ":8080"

log:
  level: "debug"
  filename: "logs/app.log"
  maxSize: 100
  maxBackups: 10
  maxAge: 7
  compress: true

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  database: "go_api_mono"
  maxOpenConns: 100
  maxIdleConns: 10
  maxLifetime: "1h"
  debug: true

jwt:
  signingKey: "your-secret-key-change-it-in-production-32"
  expirationTime: "24h"
  signingMethod: "HS256"
  tokenPrefix: "Bearer"

rateLimit:
  requests: 100    # 请求数/秒
  burst: 200       # 突发请求数